from __future__ import annotations

from html import escape
from pathlib import Path
from typing import Mapping, Sequence


def build_audit_summary(full_rows: Sequence[Mapping[str, str]], review_rows: Sequence[Mapping[str, str]]) -> dict[str, int]:
    by_market = {"US": 0, "KR": 0}
    by_asset = {"ETF": 0, "stock": 0}
    ready = 0
    review_required = len(review_rows)
    missing_selected_cagr = 0
    missing_selected_mdd = 0
    missing_selected_beta = 0
    missing_dividend_yield = 0
    kr_ticker_format_errors = 0

    for row in full_rows:
        market = row.get("market", "")
        if market in by_market:
            by_market[market] += 1
        asset_type = row.get("assetType", "")
        if asset_type in by_asset:
            by_asset[asset_type] += 1
        if row.get("dataStatus") == "ready" and row.get("reviewFlag") == "none":
            ready += 1
        if not row.get("selectedCagr"):
            missing_selected_cagr += 1
        if not row.get("selectedMdd"):
            missing_selected_mdd += 1
        if not row.get("selectedBeta"):
            missing_selected_beta += 1
        if row.get("dividendYield") == "":
            missing_dividend_yield += 1
        if market == "KR" and len(row.get("ticker", "")) != 6:
            kr_ticker_format_errors += 1

    return {
        "rowCount": len(full_rows),
        "usCount": by_market["US"],
        "krCount": by_market["KR"],
        "etfCount": by_asset["ETF"],
        "stockCount": by_asset["stock"],
        "readyCount": ready,
        "reviewRequiredCount": review_required,
        "missingSelectedCagrCount": missing_selected_cagr,
        "missingSelectedMddCount": missing_selected_mdd,
        "missingSelectedBetaCount": missing_selected_beta,
        "missingDividendYieldCount": missing_dividend_yield,
        "krTickerFormatErrors": kr_ticker_format_errors,
    }


def write_audit_report(path: Path, summary: Mapping[str, int], source_hashes: Mapping[str, str]) -> None:
    rows = "\n".join(
        f"<tr><th>{escape(str(key))}</th><td>{escape(str(value))}</td></tr>"
        for key, value in sorted(summary.items())
    )
    hashes = "\n".join(
        f"<li><code>{escape(name)}</code>: <code>{escape(sha)}</code></li>"
        for name, sha in sorted(source_hashes.items())
    )
    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>FINPLE Monthly Metrics Audit Report</title>
</head>
<body>
  <h1>FINPLE Monthly Metrics Audit Report</h1>
  <h2>Summary</h2>
  <table>{rows}</table>
  <h2>Source SHA256</h2>
  <ul>{hashes}</ul>
  <p>Generated by the Step 114-2A fixture-only pipeline. No external provider calls were made.</p>
</body>
</html>
"""
    path.write_text(html, encoding="utf-8", newline="\n")
