FULL_METRICS_COLUMNS = [
    "ticker",
    "nameKr",
    "market",
    "assetType",
    "benchmarkKey",
    "metricBaseDate",
    "dataStartDate",
    "dataEndDate",
    "dataYears",
    "priceCagr10yRaw",
    "rollingCagr10yMedian",
    "rollingCagr10yP25",
    "rollingCagr10yP75",
    "rollingCagr5yMedian",
    "sinceInceptionCagr",
    "selectedCagr",
    "cagrPolicy",
    "mdd10yRaw",
    "rollingMdd10yMedian",
    "selectedMdd",
    "mddPolicy",
    "beta10yRaw",
    "rollingBeta10yMedian",
    "rollingBeta5yMedian",
    "selectedBeta",
    "betaPolicy",
    "volatility10y",
    "dividendYield",
    "dividendPolicy",
    "dataStatus",
    "reviewFlag",
    "reviewReason",
    "sourcePolicy",
    "sourceHash",
    "notes",
]

SELECTED_COLUMNS = [
    "ticker",
    "nameKr",
    "market",
    "assetType",
    "benchmarkKey",
    "metricBaseDate",
    "dataYears",
    "selectedCagr",
    "selectedMdd",
    "selectedBeta",
    "dividendYield",
    "dataStatus",
    "reviewFlag",
    "sourcePolicy",
    "notes",
]

REVIEW_REQUIRED_COLUMNS = [
    "ticker",
    "nameKr",
    "market",
    "assetType",
    "metricBaseDate",
    "issueType",
    "rawValue",
    "selectedValue",
    "reviewReason",
    "recommendedAction",
]

MONTHLY_RETURNS_COLUMNS = [
    "market",
    "ticker",
    "month",
    "currency",
    "priceReturn",
    "totalReturn",
    "fxReturn",
    "benchmarkId",
    "isProxy",
    "proxyTicker",
    "dataStatus",
]

CANDIDATE_COLUMNS = [
    "ticker",
    "nameKr",
    "nameEn",
    "market",
    "assetType",
    "exchange",
    "sector",
    "industry",
    "strategy",
    "riskLevel",
    "goals",
    "beginnerFit",
    "tags",
    "listingDate",
    "benchmarkKey",
    "proxyTicker",
    "hedged",
    "isActive",
]

MONTHLY_PRICE_COLUMNS = [
    "ticker",
    "market",
    "month",
    "currency",
    "close",
    "cashDividend",
    "splitFactor",
    "sourceId",
    "priceAdjustmentBasis",
    "publicationEligibility",
]
