export const MOCK_ASSET_DATA = {
  QQQ: {
    name: "나스닥100 ETF",
    market: "US",
    currency: "KRW",
    price: 430000,
    cagr: 12,
    beta: 1.2,
    mdd: -35,
    dividendYield: 0.7,
  },
  SCHD: {
    name: "배당성장 ETF",
    market: "US",
    currency: "KRW",
    price: 110000,
    cagr: 8,
    beta: 0.85,
    mdd: -25,
    dividendYield: 3.5,
  },
  TLT: {
    name: "미국 장기채",
    market: "US",
    currency: "KRW",
    price: 125000,
    cagr: 4,
    beta: 0.25,
    mdd: -20,
    dividendYield: 3.8,
  },
  GLD: {
    name: "금 ETF",
    market: "US",
    currency: "KRW",
    price: 300000,
    cagr: 6,
    beta: 0.15,
    mdd: -18,
    dividendYield: 0,
  },
};
