export const PORTFOLIO_LIST_STORAGE_KEY = "finple-portfolio-list";
export const ACTIVE_PORTFOLIO_STORAGE_KEY = "finple-active-portfolio-id";
export const GLOBAL_SETTINGS_STORAGE_KEY = "finple-global-settings";
export const LEGACY_STORAGE_KEY = "finple-portfolio-simulator";
export const DEFAULT_SETTINGS = {
    monthlyCashFlow: 1000000,
    years: 10,
    dividendReinvest: true,
    inflationRate: 2.5,
  };
export const DEFAULT_ASSETS = [
    {
      ticker: "QQQ",
      name: "나스닥100 ETF",
      quantity: 50,
      price: 430000,
      cagr: 12,
      beta: 1.2,
      mdd: -35,
      dividendYield: 0.7,
    },
    {
      ticker: "SCHD",
      name: "배당성장 ETF",
      quantity: 100,
      price: 110000,
      cagr: 8,
      beta: 0.85,
      mdd: -25,
      dividendYield: 3.5,
    },
    {
      ticker: "TLT",
      name: "미국 장기채",
      quantity: 80,
      price: 125000,
      cagr: 4,
      beta: 0.25,
      mdd: -20,
      dividendYield: 3.8,
    },
    {
      ticker: "GLD",
      name: "금 ETF",
      quantity: 25,
      price: 300000,
      cagr: 6,
      beta: 0.15,
      mdd: -18,
      dividendYield: 0,
    },
  ];
export const DIVIDEND_ASSETS = [
    {
      ticker: "SCHD",
      name: "배당성장 ETF",
      quantity: 220,
      price: 110000,
      cagr: 8,
      beta: 0.85,
      mdd: -25,
      dividendYield: 3.5,
    },
    {
      ticker: "QQQ",
      name: "나스닥100 ETF",
      quantity: 25,
      price: 430000,
      cagr: 12,
      beta: 1.2,
      mdd: -35,
      dividendYield: 0.7,
    },
    {
      ticker: "TLT",
      name: "미국 장기채",
      quantity: 70,
      price: 125000,
      cagr: 4,
      beta: 0.25,
      mdd: -20,
      dividendYield: 3.8,
    },
    {
      ticker: "GLD",
      name: "금 ETF",
      quantity: 20,
      price: 300000,
      cagr: 6,
      beta: 0.15,
      mdd: -18,
      dividendYield: 0,
    },
  ];
export const STABLE_ASSETS = [
    {
      ticker: "TLT",
      name: "미국 장기채",
      quantity: 180,
      price: 125000,
      cagr: 4,
      beta: 0.25,
      mdd: -20,
      dividendYield: 3.8,
    },
    {
      ticker: "GLD",
      name: "금 ETF",
      quantity: 45,
      price: 300000,
      cagr: 6,
      beta: 0.15,
      mdd: -18,
      dividendYield: 0,
    },
    {
      ticker: "SCHD",
      name: "배당성장 ETF",
      quantity: 90,
      price: 110000,
      cagr: 8,
      beta: 0.85,
      mdd: -25,
      dividendYield: 3.5,
    },
    {
      ticker: "QQQ",
      name: "나스닥100 ETF",
      quantity: 10,
      price: 430000,
      cagr: 12,
      beta: 1.2,
      mdd: -35,
      dividendYield: 0.7,
    },
  ];
export const GROWTH_ASSETS = [
    {
      ticker: "QQQ",
      name: "나스닥100 ETF",
      quantity: 75,
      price: 430000,
      cagr: 12,
      beta: 1.2,
      mdd: -35,
      dividendYield: 0.7,
    },
    {
      ticker: "SCHD",
      name: "배당성장 ETF",
      quantity: 70,
      price: 110000,
      cagr: 8,
      beta: 0.85,
      mdd: -25,
      dividendYield: 3.5,
    },
    {
      ticker: "GLD",
      name: "금 ETF",
      quantity: 25,
      price: 300000,
      cagr: 6,
      beta: 0.15,
      mdd: -18,
      dividendYield: 0,
    },
  ];
export const EMPTY_ASSETS = [
    {
      ticker: "",
      name: "",
      quantity: 0,
      price: 0,
      cagr: 0,
      beta: 0,
      mdd: 0,
      dividendYield: 0,
    },
  ];
export const MOCK_ASSET_DATA = {
    QQQ: {
      name: "나스닥100 ETF",
      market: "US",
      currency: "KRW",
      price: 430000,
      cagr: 12,
      beta: 1.2,
      mdd: -35,
      dividendYield: 0.7,
    },
    SCHD: {
      name: "배당성장 ETF",
      market: "US",
      currency: "KRW",
      price: 110000,
      cagr: 8,
      beta: 0.85,
      mdd: -25,
      dividendYield: 3.5,
    },
    TLT: {
      name: "미국 장기채",
      market: "US",
      currency: "KRW",
      price: 125000,
      cagr: 4,
      beta: 0.25,
      mdd: -20,
      dividendYield: 3.8,
    },
    GLD: {
      name: "금 ETF",
      market: "US",
      currency: "KRW",
      price: 300000,
      cagr: 6,
      beta: 0.15,
      mdd: -18,
      dividendYield: 0,
    },
  };
