import { STEP191_AI_ML_STRATEGY_MANAGEMENT_FLAGS, buildAiMlStrategyManagementRegistry } from "./tradingAiMlStrategyManagement.js";

export const STEP192_AI_ML_DATASET_ARCHITECTURE_FLAGS = Object.freeze({
  ...STEP191_AI_ML_STRATEGY_MANAGEMENT_FLAGS,
  datasetBuildAllowed: false,
  featureGenerationAllowed: false,
  modelTrainingAllowed: false,
  modelDeploymentAllowed: false,
  modelAutoApprovalAllowed: false,
  providerCallsAllowed: false,
  orderSubmissionAllowed: false,
  dbMigrationAllowed: false,
  dbWriteAllowed: false,
  publicUiAllowed: false,
  readyForLiveGuardedTrading: false,
});

export const TRADING_AI_ML_DATASET_ARCHITECTURE_MODEL = Object.freeze({
  datasetArchitectureId: "string",
  scope: "admin_ai_ml_strategy_lab",
  status: "design_only",
  source: "deterministic_mock_dataset_registry",
  redacted: true,
  datasetFamilies: "dataset_family_definition[]",
  labelDefinitions: "label_definition_contract[]",
  featureTimestampRules: "feature_timestamp_contract[]",
  splitPolicies: "chronological_split_policy[]",
  walkForwardPolicies: "walk_forward_dataset_policy[]",
  leakageControls: "leakage_prevention_control[]",
  versioningPolicy: "dataset_versioning_policy",
  lineagePolicy: "dataset_lineage_policy",
  retentionPolicy: "dataset_retention_redaction_policy",
  blockedOperations: "blocked_operation[]",
  nextImplementationStep: "ai_ml_feature_pipeline_design_gate",
});

const DATASET_FAMILIES = Object.freeze([
  {
    datasetFamilyId: "dataset-family-market-regime-v0",
    modelType: "market_regime_classifier",
    purpose: "market regime classification",
    inputFamilies: ["market_return", "asset_return", "volatility", "volume", "moving_average_distance", "market_breadth", "rate_or_fx_change"],
    labelFamilies: ["uptrend", "sideways", "downtrend", "high_volatility"],
    pointInTimeRequired: true,
    leakageReviewStatus: "required_before_build",
    leakageRisks: ["future_label_overlap", "revision_availability", "cross_market_close_mismatch"],
    leakageControls: ["feature_available_before_prediction", "label_after_horizon_end_only", "market_timezone_aligned"],
    blockedReasons: ["dataset_build_blocked", "external_data_download_blocked"],
    redacted: true,
  },
  {
    datasetFamilyId: "dataset-family-portfolio-risk-v0",
    modelType: "portfolio_risk_score_model",
    purpose: "portfolio risk score target design",
    inputFamilies: ["allocation", "concentration", "beta", "volatility", "correlation", "drawdown", "liquidity_proxy", "asset_count"],
    labelFamilies: ["forward_realized_volatility", "forward_drawdown_bucket", "risk_event_occurrence"],
    pointInTimeRequired: true,
    leakageReviewStatus: "required_before_build",
    leakageRisks: ["future_risk_event_leakage", "post_split_imputation", "live_balance_contamination"],
    leakageControls: ["mock_snapshot_only", "split_local_imputation_only", "live_account_values_excluded"],
    blockedReasons: ["dataset_file_creation_blocked", "db_write_blocked"],
    redacted: true,
  },
  {
    datasetFamilyId: "dataset-family-downside-probability-v0",
    modelType: "downside_probability_model",
    purpose: "forward downside probability label design",
    inputFamilies: ["trailing_return", "drawdown", "volatility", "cash_buffer_placeholder", "trend"],
    labelFamilies: ["forward_return_negative", "forward_return_below_minus_5pct", "forward_drawdown_threshold_breach"],
    horizons: ["1m", "3m", "6m_candidate"],
    pointInTimeRequired: true,
    leakageReviewStatus: "required_before_build",
    leakageRisks: ["future_return_as_feature", "label_window_overlap", "random_split_leakage"],
    leakageControls: ["future_return_feature_blocked", "embargo_required", "chronological_split_only"],
    blockedReasons: ["training_blocked", "feature_generation_blocked"],
    redacted: true,
  },
  {
    datasetFamilyId: "dataset-family-volatility-forecast-v0",
    modelType: "volatility_forecast_model",
    purpose: "future realized volatility target design",
    inputFamilies: ["realized_volatility", "range_proxy", "shock_flag_placeholder", "rate_change", "fx_change"],
    labelFamilies: ["future_realized_volatility"],
    horizons: ["5d_candidate", "20d_candidate", "60d_candidate"],
    pointInTimeRequired: true,
    leakageReviewStatus: "required_before_build",
    leakageRisks: ["future_volatility_overlap", "full_period_normalization", "provider_quote_dependency"],
    leakageControls: ["purged_overlap_samples", "fit_normalizer_on_train_only", "provider_quote_blocked"],
    blockedReasons: ["provider_call_blocked", "dataset_artifact_blocked"],
    redacted: true,
  },
  {
    datasetFamilyId: "dataset-family-rebalancing-necessity-v0",
    modelType: "rebalancing_necessity_model",
    purpose: "rebalance necessity review label design",
    inputFamilies: ["allocation_drift", "volatility_change", "concentration", "risk_score", "transaction_cost_estimate"],
    labelFamilies: ["rule_based_rebalance_triggered", "post_rebalance_risk_improvement_candidate", "admin_reviewed_rebalance_necessity_placeholder"],
    pointInTimeRequired: true,
    leakageReviewStatus: "required_before_build",
    leakageRisks: ["post_rebalance_outcome_leakage", "admin_review_timestamp_leakage", "actual_order_contamination"],
    leakageControls: ["label_after_review_window_only", "admin_review_available_at_required", "actual_order_values_excluded"],
    blockedReasons: ["order_linkage_blocked", "auto_trading_blocked"],
    redacted: true,
  },
]);

const LABEL_DEFINITIONS = Object.freeze([
  {
    labelId: "downside_1m_negative",
    modelType: "downside_probability_model",
    labelName: "one month negative forward return",
    horizon: "1m",
    formula: "forward_return_1m < 0",
    threshold: 0,
    positiveClass: "negative_forward_return",
    neutralClass: "non_negative_forward_return",
    missingLabelPolicy: "exclude_until_label_end_time_available",
    embargoPeriod: "1m",
    redacted: true,
  },
  {
    labelId: "downside_3m_below_minus_5pct",
    modelType: "downside_probability_model",
    labelName: "three month downside threshold breach",
    horizon: "3m",
    formula: "forward_return_3m < -5pct",
    threshold: "-5pct",
    positiveClass: "below_threshold",
    neutralClass: "at_or_above_threshold",
    missingLabelPolicy: "exclude_until_label_end_time_available",
    embargoPeriod: "3m",
    redacted: true,
  },
  {
    labelId: "forward_volatility_20d",
    modelType: "volatility_forecast_model",
    labelName: "future realized volatility twenty day",
    horizon: "20d",
    formula: "realized_volatility_over_label_window",
    threshold: "continuous_target",
    positiveClass: "not_applicable_continuous",
    neutralClass: "not_applicable_continuous",
    missingLabelPolicy: "exclude_until_label_end_time_available",
    embargoPeriod: "20d",
    redacted: true,
  },
  {
    labelId: "future_drawdown_bucket_60d",
    modelType: "portfolio_risk_score_model",
    labelName: "future drawdown bucket sixty day",
    horizon: "60d",
    formula: "max_drawdown_over_label_window_bucket",
    threshold: "bucketed_thresholds",
    positiveClass: "high_drawdown_bucket",
    neutralClass: "low_or_medium_drawdown_bucket",
    missingLabelPolicy: "exclude_until_label_end_time_available",
    embargoPeriod: "60d",
    redacted: true,
  },
  {
    labelId: "market_regime_20d",
    modelType: "market_regime_classifier",
    labelName: "twenty day market regime",
    horizon: "20d",
    formula: "future_return_and_volatility_bucket_after_prediction_time",
    threshold: "deterministic_bucket_rules",
    positiveClass: "regime_bucket",
    neutralClass: "sideways_bucket",
    missingLabelPolicy: "exclude_until_label_end_time_available",
    embargoPeriod: "20d",
    redacted: true,
  },
]);

const FEATURE_TIMESTAMP_RULES = Object.freeze([
  {
    featureId: "return_5d",
    featureName: "five day trailing return",
    sourceFamily: "market_or_asset_return",
    lookbackWindow: "5d",
    calculationFrequency: "daily_after_market_close",
    availableAtRule: "next_market_close_plus_vendor_lag_placeholder",
    normalization: "train_split_fit_only",
    missingValuePolicy: "drop_until_window_complete",
    leakageRisk: "low_with_available_at_enforced",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "return_20d",
    featureName: "twenty day trailing return",
    sourceFamily: "market_or_asset_return",
    lookbackWindow: "20d",
    calculationFrequency: "daily_after_market_close",
    availableAtRule: "observation_time_after_close_only",
    normalization: "train_split_fit_only",
    missingValuePolicy: "drop_until_window_complete",
    leakageRisk: "low_with_window_purge",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "volatility_20d",
    featureName: "twenty day trailing volatility",
    sourceFamily: "volatility",
    lookbackWindow: "20d",
    calculationFrequency: "daily_after_market_close",
    availableAtRule: "prediction_time_must_be_after_available_at",
    normalization: "train_split_fit_only",
    missingValuePolicy: "drop_until_window_complete",
    leakageRisk: "medium_if_overlap_not_purged",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "drawdown_60d",
    featureName: "sixty day trailing drawdown",
    sourceFamily: "drawdown",
    lookbackWindow: "60d",
    calculationFrequency: "daily_after_market_close",
    availableAtRule: "uses_only_prior_observations",
    normalization: "not_required",
    missingValuePolicy: "drop_until_window_complete",
    leakageRisk: "medium_if_current_window_uses_future_peak",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "momentum_120d",
    featureName: "one hundred twenty day momentum",
    sourceFamily: "trend",
    lookbackWindow: "120d",
    calculationFrequency: "daily_after_market_close",
    availableAtRule: "prediction_time_after_all_inputs_available",
    normalization: "train_split_fit_only",
    missingValuePolicy: "drop_until_window_complete",
    leakageRisk: "low_with_chronological_split",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "beta_252d",
    featureName: "two hundred fifty two day beta",
    sourceFamily: "portfolio_risk",
    lookbackWindow: "252d",
    calculationFrequency: "daily_after_market_close",
    availableAtRule: "benchmark_and_asset_inputs_available_before_prediction",
    normalization: "train_split_fit_only",
    missingValuePolicy: "flag_and_exclude_until_window_complete",
    leakageRisk: "medium_if_benchmark_calendar_misaligned",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "allocation_drift",
    featureName: "allocation drift from target",
    sourceFamily: "portfolio_allocation",
    lookbackWindow: "snapshot_at_prediction_time",
    calculationFrequency: "mock_snapshot",
    availableAtRule: "mock_snapshot_available_at_before_prediction",
    normalization: "not_required",
    missingValuePolicy: "block_dataset_row",
    leakageRisk: "high_if_post_rebalance_snapshot_used",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "concentration_hhi",
    featureName: "portfolio concentration hhi",
    sourceFamily: "portfolio_risk",
    lookbackWindow: "snapshot_at_prediction_time",
    calculationFrequency: "mock_snapshot",
    availableAtRule: "mock_snapshot_available_at_before_prediction",
    normalization: "not_required",
    missingValuePolicy: "block_dataset_row",
    leakageRisk: "high_if_live_balance_values_used",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "fx_change_20d",
    featureName: "twenty day fx change",
    sourceFamily: "macro_market",
    lookbackWindow: "20d",
    calculationFrequency: "daily_after_market_close",
    availableAtRule: "macro_release_available_at_required",
    normalization: "train_split_fit_only",
    missingValuePolicy: "flag_and_forward_fill_within_train_only",
    leakageRisk: "medium_if_release_timestamp_ignored",
    version: "feature_timestamp_v0",
    redacted: true,
  },
  {
    featureId: "rate_change_20d",
    featureName: "twenty day interest rate change",
    sourceFamily: "macro_market",
    lookbackWindow: "20d",
    calculationFrequency: "daily_after_release",
    availableAtRule: "release_timestamp_before_prediction_time",
    normalization: "train_split_fit_only",
    missingValuePolicy: "flag_and_forward_fill_within_train_only",
    leakageRisk: "medium_if_revision_policy_ignored",
    version: "feature_timestamp_v0",
    redacted: true,
  },
]);

const POINT_IN_TIME_RULES = Object.freeze({
  requiredFields: ["observationTime", "availableAt", "predictionTime", "labelStartTime", "labelEndTime", "marketTimezone", "dataRevisionPolicy"],
  rules: [
    "feature values must be available before prediction time",
    "fundamental dividend and corporate action values use availability time not final restated time",
    "delisting and listing membership are resolved as of prediction time",
    "fx and rate values respect release timestamps",
    "market close and timezone boundaries are explicit",
    "us and kr market calendars are aligned without future availability",
    "label is finalized only after label end time",
  ],
  status: "design_only",
  redacted: true,
});

const SPLIT_POLICIES = Object.freeze([
  {
    splitPolicyId: "chronological-split-v0",
    policyType: "chronological",
    randomSplitAllowed: false,
    trainWindow: "2015-01-01_to_2021-12-31",
    validationWindow: "2022-01-01_to_2023-12-31",
    testWindow: "2024-01-01_to_2025-12-31",
    finalHoldoutPolicy: "preserve_unseen_holdout",
    embargoRule: "label_horizon_sized_embargo",
    purgeRule: "purge_overlapping_samples",
    imputationRule: "fit_with_train_split_only",
    redacted: true,
  },
]);

const WALK_FORWARD_POLICIES = Object.freeze([
  {
    walkForwardPolicyId: "walk-forward-expanding-v0",
    windowType: "expanding_train_rolling_validation",
    trainWindowMinimum: "36m",
    validationWindow: "6m",
    testWindow: "6m",
    stepSize: "3m",
    embargoRule: "apply_label_horizon_embargo_each_fold",
    foldLeakageCheck: "required_before_training",
    redacted: true,
  },
]);

const LEAKAGE_CONTROLS = Object.freeze([
  "future return feature blocked",
  "full period normalization blocked",
  "post split imputation blocked",
  "feature and label window overlap checked",
  "random shuffle split blocked by default",
  "survivorship bias review required",
  "lookahead bias review required",
  "duplicate timestamp review required",
  "target leakage review required",
  "corporate action revision leakage review required",
  "cross asset future availability review required",
]);

const VERSIONING_POLICY = Object.freeze({
  policyId: "dataset-versioning-policy-v0",
  datasetVersionFormat: "dataset_family_id:label_version:feature_version:split_version",
  labelChangeCreatesNewDatasetVersion: true,
  featureChangeCreatesNewDatasetVersion: true,
  splitChangeCreatesNewDatasetVersion: true,
  immutableAfterReview: true,
  status: "design_only",
  redacted: true,
});

const LINEAGE_POLICY = Object.freeze({
  policyId: "dataset-lineage-policy-v0",
  lineageFields: ["sourceRegistryId", "datasetFamilyId", "labelDefinitionId", "featureSetVersion", "splitPolicyId", "walkForwardPolicyId", "createdByAdminPlaceholder"],
  rawValueStorageAllowed: false,
  privatePathStorageAllowed: false,
  digestStorageAllowed: false,
  status: "placeholder_only",
  redacted: true,
});

const RETENTION_POLICY = Object.freeze({
  policyId: "dataset-retention-redaction-policy-v0",
  retentionScope: "metadata_contract_only",
  datasetFileRetention: "not_applicable_no_file_created",
  redactionRequired: true,
  forbiddenValueClasses: ["secret material", "account linkage values", "provider packets", "order packets", "private filesystem references", "raw hash or digest material"],
  publicExposureAllowed: false,
  mypageExposureAllowed: false,
  redacted: true,
});

const BLOCKED_OPERATIONS = Object.freeze([
  "actual_data_download",
  "external_financial_api_call",
  "kis_or_provider_call",
  "python_training_job",
  "model_training",
  "model_artifact_creation",
  "dataset_file_creation",
  "csv_or_parquet_creation",
  "supabase_select_insert_update_delete",
  "db_migration_or_schema_change",
  "persistent_db_write",
  "order_submission_or_live_account_query",
  "public_or_mypage_ai_ml_ui",
  "user_investment_recommendation_output",
]);

const IMPLEMENTATION_CONTRACTS = Object.freeze([
  { step: "Step 193", name: "AI/ML feature pipeline design gate", allowedScope: "feature_contract_only_no_generation_no_file" },
  { step: "Step 194", name: "AI/ML training dataset build preflight", allowedScope: "build_preflight_only_no_data_download_no_db_write" },
  { step: "Step 195", name: "AI/ML model training preflight", allowedScope: "training_preflight_only_no_python_job_no_artifact" },
]);

function validateDatasetArchitecture(architecture) {
  const blockers = [];
  const expectedFamilies = new Set([
    "market_regime_classifier",
    "portfolio_risk_score_model",
    "downside_probability_model",
    "volatility_forecast_model",
    "rebalancing_necessity_model",
  ]);
  for (const family of architecture.datasetFamilies) {
    expectedFamilies.delete(family.modelType);
    if (family.redacted !== true) blockers.push(`${family.datasetFamilyId}_not_redacted`);
    if (family.pointInTimeRequired !== true) blockers.push(`${family.datasetFamilyId}_point_in_time_not_required`);
    if (family.leakageReviewStatus !== "required_before_build") blockers.push(`${family.datasetFamilyId}_leakage_review_not_required`);
  }
  if (expectedFamilies.size > 0) blockers.push(`missing_dataset_families:${Array.from(expectedFamilies).join(",")}`);
  if (architecture.splitPolicies.some((policy) => policy.randomSplitAllowed !== false)) blockers.push("random_split_enabled");
  if (architecture.labelDefinitions.some((label) => label.redacted !== true || !label.embargoPeriod)) blockers.push("label_definition_not_redacted_or_missing_embargo");
  if (architecture.featureTimestampRules.some((feature) => !feature.availableAtRule || feature.redacted !== true)) blockers.push("feature_timestamp_rule_incomplete");
  if (architecture.versioningPolicy.labelChangeCreatesNewDatasetVersion !== true) blockers.push("label_change_versioning_disabled");
  if (architecture.lineagePolicy.rawValueStorageAllowed !== false) blockers.push("lineage_raw_value_storage_enabled");
  if (architecture.retentionPolicy.redactionRequired !== true) blockers.push("retention_redaction_not_required");

  return {
    validationStatus: blockers.length > 0 ? "blocked" : "design_ready",
    blockers,
    warnings: ["dataset_build_not_started", "feature_generation_not_started", "training_pipeline_not_started"],
    redacted: true,
  };
}

export function buildAiMlDatasetArchitecture(input = {}) {
  const strategyRegistry = input.strategyRegistry || buildAiMlStrategyManagementRegistry(input);
  const architecture = {
    datasetArchitectureId: "step192_admin_ai_ml_dataset_architecture",
    scope: "admin_ai_ml_strategy_lab",
    status: "design_only",
    source: "deterministic_mock_dataset_registry",
    strategyRegistryId: strategyRegistry.registryId,
    redacted: true,
    datasetFamilies: input.datasetFamilies || DATASET_FAMILIES,
    labelDefinitions: input.labelDefinitions || LABEL_DEFINITIONS,
    featureTimestampRules: input.featureTimestampRules || FEATURE_TIMESTAMP_RULES,
    pointInTimeRules: POINT_IN_TIME_RULES,
    splitPolicies: input.splitPolicies || SPLIT_POLICIES,
    walkForwardPolicies: input.walkForwardPolicies || WALK_FORWARD_POLICIES,
    leakageControls: [...LEAKAGE_CONTROLS],
    versioningPolicy: VERSIONING_POLICY,
    lineagePolicy: LINEAGE_POLICY,
    retentionPolicy: RETENTION_POLICY,
    blockedOperations: [...BLOCKED_OPERATIONS],
    implementationContracts: IMPLEMENTATION_CONTRACTS,
    nextImplementationStep: "ai_ml_feature_pipeline_design_gate",
  };

  return {
    ...architecture,
    datasetFamilyCount: architecture.datasetFamilies.length,
    labelDefinitionCount: architecture.labelDefinitions.length,
    featureTimestampRuleCount: architecture.featureTimestampRules.length,
    leakageControlCount: architecture.leakageControls.length,
    splitPolicyCount: architecture.splitPolicies.length,
    walkForwardPolicyCount: architecture.walkForwardPolicies.length,
    validation: validateDatasetArchitecture(architecture),
    datasetBuildStatus: "blocked",
    featureGenerationStatus: "blocked",
    trainingStatus: "blocked",
    dbWriteStatus: "blocked",
    providerOrderLiveStatus: "blocked",
  };
}

export function buildAdminTradingAiMlDatasetArchitectureStatus(input = {}) {
  const datasetArchitecture = input.datasetArchitecture || buildAiMlDatasetArchitecture(input);
  return {
    ok: true,
    step: "Step 192: Design AI/ML dataset and labeling architecture",
    status: "admin_only_ai_ml_dataset_architecture_design_only",
    sourceStep: "step192",
    datasetArchitectureModel: TRADING_AI_ML_DATASET_ARCHITECTURE_MODEL,
    datasetArchitecture,
    blockedConfirmation: {
      endpointAdded: false,
      actualDataDownloadAttempted: false,
      externalFinancialApiCallAttempted: false,
      providerCallAttempted: false,
      tokenIssuanceAttempted: false,
      quoteQueryAttempted: false,
      pythonTrainingJobAttempted: false,
      modelTrainingAttempted: false,
      modelArtifactCreated: false,
      datasetFileCreated: false,
      csvOrParquetCreated: false,
      supabaseSelectAttempted: false,
      supabaseInsertAttempted: false,
      supabaseUpdateAttempted: false,
      supabaseDeleteAttempted: false,
      dbMigrationAttempted: false,
      dbSchemaChangeAttempted: false,
      persistentDbWriteAttempted: false,
      orderSubmissionAttempted: false,
      liveAccountBalanceQueried: false,
      mypageAiMlUiExposed: false,
      homepageAiMlUiExposed: false,
      publicAiMlUiExposed: false,
      userInvestmentRecommendationExposed: false,
      redacted: true,
    },
    flags: { ...STEP192_AI_ML_DATASET_ARCHITECTURE_FLAGS },
    datasetBuildAllowed: false,
    featureGenerationAllowed: false,
    modelTrainingAllowed: false,
    modelDeploymentAllowed: false,
    modelAutoApprovalAllowed: false,
    providerCallsAllowed: false,
    orderSubmissionAllowed: false,
    dbMigrationAllowed: false,
    dbWriteAllowed: false,
    publicUiAllowed: false,
    readyForLiveGuardedTrading: false,
    persistentStorageUsed: false,
    dbWriteUsed: false,
    redacted: true,
  };
}
