const assert = require("node:assert/strict");
const fs = require("node:fs");
const test = require("node:test");

test("Step 161 checker covers mock trading run summary core implementation and safety boundaries", () => {
  const checkText = fs.readFileSync("scripts/check-trading-step161-admin-trading-lab-mock-trading-run-summary-core.cjs", "utf8");
  const packageText = fs.readFileSync("package.json", "utf8");

  assert.match(checkText, /STEP161_ADMIN_TRADING_LAB_MOCK_TRADING_RUN_SUMMARY_CORE_FLAGS/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_SUMMARY_CORE_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_SUMMARY_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_STRATEGY_SUMMARY_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_ORDER_EXECUTION_FILL_SUMMARY_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_LEDGER_SUMMARY_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_PERFORMANCE_SUMMARY_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_RISK_SAFETY_SUMMARY_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_DASHBOARD_AGGREGATION_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_CHART_AGGREGATION_RESULT_MODEL/);
  assert.match(checkText, /TRADING_LAB_MOCK_TRADING_RUN_SUMMARY_RESULT_SCHEMA/);
  assert.match(checkText, /validateTradingLabMockTradingRunSummaryCore/);
  assert.match(checkText, /buildTradingLabMockTradingRunSummaryCore/);
  assert.match(checkText, /buildTradingLabMockTradingRunDashboardAggregationResult/);
  assert.match(checkText, /buildTradingLabMockTradingRunChartAggregationResult/);
  assert.match(checkText, /buildAdminTradingLabMockTradingRunSummaryCoreStatus/);
  assert.match(checkText, /trading-lab-mock-trading-run-summary-core/);
  assert.match(checkText, /requireAdminAccess/);
  assert.match(checkText, /AccountPages\.jsx/);
  assert.match(checkText, /src\/App\.jsx/);
  assert.match(checkText, /scenario_monthly_returns\.csv/);
  assert.match(checkText, /scenario runtime files must remain untouched/);
  assert.match(checkText, /providerCallsAllowed: true/);
  assert.match(checkText, /orderSubmissionAllowed: true/);
  assert.match(checkText, /kisOrderPayloadCreated: true/);
  assert.match(checkText, /kisExecutionPayloadCreated: true/);
  assert.match(checkText, /kisFillPayloadCreated: true/);
  assert.match(checkText, /executionRecordCreated: true/);
  assert.match(checkText, /fillRecordCreated: true/);
  assert.match(checkText, /portfolioLedgerPersisted: true/);
  assert.match(checkText, /performanceRecordPersisted: true/);
  assert.match(checkText, /accountBalanceQueried: true/);
  assert.match(checkText, /actualCashUpdated: true/);
  assert.match(checkText, /actualPositionUpdated: true/);
  assert.match(checkText, /actualPerformanceRecordUpdated: true/);
  assert.match(checkText, /realTradingRunIdentifierCreated: true/);
  assert.match(checkText, /actualInvestmentPerformanceConfirmed: true/);
  assert.match(checkText, /returnGuaranteeProvided: true/);
  assert.match(checkText, /investmentAdviceProvided: true/);
  assert.match(packageText, /check:trading-step161-admin-trading-lab-mock-trading-run-summary-core/);
});
